### PR TITLE
Bugfix 34 default browser configurations not being read

### PR DESCRIPTION
**Pull request by ty-desj**
Fixed incorrect reference to an attribute. Default configurations are now read from file correctly.

### CODE REVIEW

**Comment by DominicParent** [comment]
@ty-desj When running the tests on the VM, I'm getting an issue in the tests/actions/test_selenium.py file about the lines with "browser.browser". It says that "AttributeError: type object 'ChromeDriver' has no attribute 'browser'".

Have you encountered anything like this?

**Comment by ty-desj** [comment]
Yup, I know exactly the issue! I had a no brain moment and forgot to include a change in the push. Will correct it and update the PR when it is ready!

**Comment by ty-desj** [comment]
@DominicParent the PR is _actually_ ready for review this time. The good news, is that in going back to push the missing commit, I thought of a better, more detailed way of passing the error message to the subtests instead of just the browser name.

**Review by DominicParent — APPROVED** [review]

**Comment by DominicParent** [comment]
@ty-desj All seems good.

**Pull request merged**
