### PR TITLE
Doc 31 update documentation

### LINKED ISSUE #31: Create user documentation about framework

### PR DESCRIPTION
**Pull request by DominicParent**
Closes #31.

### CODE REVIEW

**Comment by DominicParent** [comment]
@ty-desj I tried to recreate the error I got for the code comments, but I wasn't able to.

Could you try to generate the documents and see if you get the errors? Maybe it was just a one off.

**Comment by ty-desj** [comment]
@DominicParent Sure thing, what is the command to generate them?

**Comment by DominicParent** [comment]
@ty-desj The documentation can be built using the `sphinx-build -b html source build` from the doc folder.

**Comment by DominicParent** [comment]
@ty-desj You'll have to add stuff in your conda environment (sphinx and myst-parser) but I've added those to the environment creation file.

**Pull request merged**
